apiVersion: v1
kind: Template
metadata:
  name: f8notification-config
  creationTimestamp: null
objects:
- apiVersion: v1
  kind: Secret
  metadata:
    name: f8notification
  type: Opaque
  data:
    madrill.api: eHh4eHh4
- apiVersion: v1
  kind: ConfigMap
  metadata:
    name: f8notification
  type: Opaque
  data:
    wit.api: https://api.prod-preview.openshift.io
    auth.api: https://auth.prod-preview.openshift.io
    keycloak.url: https://sso.prod-preview.openshift.io
    keycloak.realm: fabric8-test