apiVersion: v1
kind: Template
metadata:
  name: f8notification-config
  creationTimestamp: null
objects:
- apiVersion: v1
  kind: Secret
  metadata:
    name: f8notification
  type: Opaque
  data:
    madrill.api: eHh4eHh4
    service.account.id: NGM4M2NhMmQtNmRjYy00MWM5LWFjN2QtYjA2OGFkNGQxN2M1
    service.account.secret: bm90aWZpY2F0aW9uc2VjcmV0
- apiVersion: v1
  kind: ConfigMap
  metadata:
    name: f8notification
  type: Opaque
  data:
    wit.url: https://api.prod-preview.openshift.io
    auth.url: https://auth.prod-preview.openshift.io